apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit-sa
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wskorea26-fluentbit-role
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wskorea26-fluentbit-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wskorea26-fluentbit-role
subjects:
- kind: ServiceAccount
  name: fluentbit-sa
  namespace: logging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level     info
        Parsers_File  parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*_wskorea26_*.log
        Parser            cri
        Tag               kube.*
        Refresh_Interval  5
        Mem_Buf_Limit     5MB

    [FILTER]
        Name             kubernetes
        Match            kube.*
        Kube_URL         https://kubernetes.default.svc:443
        Kube_Tag_Prefix  kube.var.log.containers.
        Merge_Log        Off
        Keep_Log         On
        K8S-Logging.Parser Off
        Labels           On
        Annotations      Off
        tls.verify       Off

    [OUTPUT]
        Name              cloudwatch_logs
        Match             kube.*
        region            ap-northeast-2
        log_group_name    /wskorea26/application
        log_stream_prefix book-
        auto_create_group false

  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wskorea26-fluentbit
  namespace: logging
spec:
  selector:
    matchLabels:
      name: wskorea26-fluentbit
  template:
    metadata:
      labels:
        name: wskorea26-fluentbit
    spec:
      serviceAccountName: fluentbit-sa
      nodeSelector:
        node-type: addon
      containers:
      - name: fluent-bit
        image: public.ecr.aws/aws-observability/aws-for-fluent-bit:latest
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: config
          mountPath: /fluent-bit/etc/
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: config
        configMap:
          name: fluentbit-config
