adminUser: skills-${pin_number}-admin
adminPassword: '\$korea26!!'
service:
  type: ClusterIP
  port: 3000
nodeSelector:
  node-type: addon
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: wskorea26-prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc:80
      access: proxy
      isDefault: true
    - name: wskorea26-logs
      type: cloudwatch
      access: proxy
      jsonData:
        defaultRegion: ap-northeast-2
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: default
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    wskorea26-monitoring:
      json: |
        {
          "uid": "wskorea26",
          "title": "wskorea26-monitoring",
          "panels": [
            {
              "title": "Book CPU Utilization",
              "type": "timeseries",
              "datasource": "wskorea26-prometheus",
              "targets": [{"expr": "rate(container_cpu_usage_seconds_total{namespace=\"wskorea26\",container=\"book\"}[5m])"}],
              "gridPos": {"h": 12, "w": 24, "x": 0, "y": 0}
            }
          ],
          "schemaVersion": 38,
          "version": 1
        }
