apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wsc2026-book-ingress
  namespace: wsc2026
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/load-balancer-name: wsc2026-app-alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: "8080"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/security-groups: PLACEHOLDER_ALB_SG
    alb.ingress.kubernetes.io/subnets: PLACEHOLDER_SUBNETS
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wsc2026-book-svc
                port:
                  number: 8080
